//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace eyeSign {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings1 : ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string LoadedInkLocation {
            get {
                return ((string)(this["LoadedInkLocation"]));
            }
            set {
                this["LoadedInkLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowDotWhenWriting {
            get {
                return ((bool)(this["ShowDotWhenWriting"]));
            }
            set {
                this["ShowDotWhenWriting"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowTranslucentInkWhenWriting {
            get {
                return ((bool)(this["ShowTranslucentInkWhenWriting"]));
            }
            set {
                this["ShowTranslucentInkWhenWriting"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string InkMatrix {
            get {
                return ((string)(this["InkMatrix"]));
            }
            set {
                this["InkMatrix"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color InkColor {
            get {
                return ((Color)(this["InkColor"]));
            }
            set {
                this["InkColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("64, 255, 255, 255")]
        public Color FadedInkColor {
            get {
                return ((Color)(this["FadedInkColor"]));
            }
            set {
                this["FadedInkColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double InkWidth {
            get {
                return ((double)(this["InkWidth"]));
            }
            set {
                this["InkWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("128, 254, 212, 42")]
        public Color DotColor {
            get {
                return ((Color)(this["DotColor"]));
            }
            set {
                this["DotColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public double DotWidth {
            get {
                return ((double)(this["DotWidth"]));
            }
            set {
                this["DotWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("40")]
        public int AnimationInterval {
            get {
                return ((int)(this["AnimationInterval"]));
            }
            set {
                this["AnimationInterval"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public int AnimationPointsOnFirstStroke {
            get {
                return ((int)(this["AnimationPointsOnFirstStroke"]));
            }
            set {
                this["AnimationPointsOnFirstStroke"] = value;
            }
        }
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com7")]
        public string RobotComPort {
            get {
                return ((string)(this["RobotComPort"]));
            }
            set {
                this["RobotComPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1.66")]
        public double RobotZShift {
            get {
                return ((double)(this["RobotZShift"]));
            }
            set {
                this["RobotZShift"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.35")]
        public double RobotWorkspaceScale {
            get {
                return ((double)(this["RobotWorkspaceScale"]));
            }
            set {
                this["RobotWorkspaceScale"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool RobotControl {
            get {
                return ((bool)(this["RobotControl"]));
            }
            set {
                this["RobotControl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public double DotDownWidth {
            get {
                return ((double)(this["DotDownWidth"]));
            }
            set {
                this["DotDownWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("254, 212, 42")]
        public Color DotDownColor {
            get {
                return ((Color)(this["DotDownColor"]));
            }
            set {
                this["DotDownColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color BackgroundColor {
            get {
                return ((Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("254, 212, 42")]
        public Color ButtonBackgroundColor {
            get {
                return ((Color)(this["ButtonBackgroundColor"]));
            }
            set {
                this["ButtonBackgroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color ButtonTextColor {
            get {
                return ((Color)(this["ButtonTextColor"]));
            }
            set {
                this["ButtonTextColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color ButtonBorderColor {
            get {
                return ((Color)(this["ButtonBorderColor"]));
            }
            set {
                this["ButtonBorderColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public double ButtonBorderWidth {
            get {
                return ((double)(this["ButtonBorderWidth"]));
            }
            set {
                this["ButtonBorderWidth"] = value;
            }
        }
    }
}
